config/routes.rb
Rails.application.routes.draw do
  resources :credits, only: [:index, :show, :new, :create, :edit]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'users#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  
  get '/credit/:user_id', to: 'credits#index', as: 'credit_user_id'

end

app/models/credit.rb
class Credit < ActiveRecord::Base

def create_amount(income,percent,term)
self.amount = income.to_f * (1 + percent.to_f * (term.to_f / 12))
end

def add_percent(percent)
self.percent = percent
end
end

app/models/user.rb
class User < ActiveRecord::Base
 before_save { self.email = email.downcase }
 before_create :create_remember_token

 validates :name, presence: true, length: { minimum: 3,maximum: 50 }
 VALID_EMAIL_REGEX = /\A([a-z0-9_-]+\.)*[a-z0-9_-]+@[a-z0-9_-]+(\.[a-z0-9_-]+)*\.[a-z]{2,6}|z/i
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
 VALID_INCOME_REGEX = /\d+(\.\d{0,})?/
 validates :income, presence: true, format: { with: VALID_INCOME_REGEX }
 has_secure_password
 validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def add_percent(income)
    if income.to_f > 100000
	   self.percent = 0.5
	end   
    if income.to_f <= 100000
	   self.percent = 0.2
	end   
    if income.to_f <= 10000
	   self.percent = 0.1
	end   
    if income.to_f <= 1000
	   self.percent = 0.05
	end   
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:index, :new, :show, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  # GET /credits
  # GET /credits.json
  def index
     if !params[:user_id].nil?
     user = User.find(params[:user_id])
	 end
     if user.nil?
	 user_email = current_user.email.to_s
	 @credits = Credit.where("email = ?", user_email)
	 else
    @credits = Credit.where("email = ?", user.email)
	end
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
	@credit.add_percent(current_user.percent)
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)
    @credit.email = current_user.email
	@credit.create_amount(@credit.amount, current_user.percent, @credit.term)
    respond_to do |format|
      if @credit.save
        format.html { redirect_to '/credits', notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to '/credits', notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:email, :amount, :term, :payment, :status)
    end
	
    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    sign_in user
	if user.admin
      redirect_to "/users"
	  else
	  redirect_to "/credits"
	  end
  else
    flash[:error] = 'Invalid email/password combination'
      render 'new'
  end
  def redirect_start_page
     redirect_to '/credits'
  end
  end
  def destroy
    sign_out
    redirect_to root_url
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
     if current_user.nil?
       redirect_to '/signin'
	   else
       if !current_user.admin
       redirect_to '/credits'
       end
       @users = User.all
     end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.add_percent(@user.income)
    
    respond_to do |format|
      if @user.save
	  sign_in
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.add_percent(@user.income)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	
    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :income)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies[:remember_token] = { value: remember_token, expires: 4.weeks.from_now.utc }
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user || current_user.admin
  end

  def signed_in?
    !current_user.nil?
  end
  
  
  
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Your percent: " %>
    <%= @credit.percent.to_f * 100 %>%
  </div>
  <div class="field">
    <%= f.label "Payment period(in month)" %><br>
    <%= f.number_field :term %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credits</h1>

<table class="features-table">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Term</th>
      <th>Payment</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.amount %></td>
        <td><%= credit.term %> months</td>
        <td><%= credit.payment %></td>
        <td><%= credit.status %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<br>

		<%if !current_user.admin%>
<%= link_to 'New Credit', new_credit_path %>
		<%end%>

app/views/credits/new.html.erb
<h1>New Credit</h1>

<%= render 'form' %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @credit.email %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @credit.amount %>
</p>

<p>
  <strong>Term:</strong>
  <%= @credit.term %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @credit.payment %>
</p>

<p>
  <strong>Status:</strong>
  <%= @credit.status %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>

<table class="features-table">
  <thead>
    <tr>
      <th>Month</th>
      <th>Payment</th>
      <th>Recidue</th>
    </tr>
  </thead>

  <tbody>
    <%recidue = @credit.amount.to_f %>
	<%m=0.01%>
    <% 1.upto(@credit.term.to_i) do |n|%>
	<%if n == @credit.term.to_i%>
	<%m = 0%>
	<%end%>
    <%payment = recidue / (@credit.term.to_i - n + 1) + m %>
	<%recidue = recidue - payment %>
      <tr>
        <td><%= @credit.created_at.months_since(n).strftime("%Y-%m") %></td>
        <td><%= payment.round(2) %></td>
        <td><%= recidue.round(2) %></td>
      </tr>
	  <%end%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse" style="background: #e3a555;">
      <div class="navbar-inner">
        <div class="container">
		<%= link_to "MoneyZen_Ruby", '/', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              <li><%= link_to "Welcome, "+current_user.name,    '/users/'+current_user.id.to_s %></li>
			  <li><b style="padding: 10px 15px;"></b></li>
              <% else %>
              <li><%= link_to "Sign in",    '/signin' %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
	
	<style>
	.nav li
	{
	float: inherit;
	}
	</style>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :income %><br>
    <%= f.text_field :income %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit yield(:btn), class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "New User") %>
<%= provide( :btn, "Save")%>
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: "btn btn-large btn-primary" %>
<%= link_to 'Back', users_path, class: "btn btn-large btn-primary" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="features-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Income</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.income %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Credits', '/credit/' + user.id.to_s %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-large btn-primary" %>

app/views/users/new.html.erb
<% provide(:title, "New User") %>
<h1>New User</h1>
<%= provide( :btn, "Create")%>
<%= render 'form' %>

<%= link_to 'Back', users_path, class: "btn btn-large btn-primary" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Percent: </strong>
  <%= @user.percent %>
</p>

<p>
  <strong>Income:</strong>
  <%= @user.income %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>